let schemas = {
	table: 'Sys_User',
	primaryKeyColumn: 'UsersId',
	UsersId: 'int',
	EmployeeCode: 'string',
	CompanyId: 'Int64',
	DepartmentId: 'Int64',
	PositionId: 'Int64',
	LastName: 'string',
	FirstName: 'string',
	UserName: 'string',
	UserName_Encrypted: 'string',
	Password: 'string',
	Birthday: 'DateTime',
	Sex: 'string',
	Email: 'string',
	PhoneNumber: 'string',
	Address: 'string',
	District: 'Int64',
	Provincial: 'Int64',
	Nation: 'string',
	IsManagement: 'int',
	Status: 'string',
	LastLoginTime: 'DateTime',
	Avatar: 'string',
	ReceiveEmail: 'int',
	ReceiveSMS: 'int',
	FullPathTemporarySave: 'string',
	TemporaryFileName: 'string',
	PathTemporarySave: 'string',
	ManagerCode: 'Int64',
	LinkChangePassword: 'string',
	TokenChangePassword: 'string',
	NotificationTimeChangedPassword: 'DateTime',
	TimeChangedPassword: 'DateTime',
	BrowserHeaders: 'string',
	StatusLogin: 'int',
	User_Id_Created: 'int',
	User_Name_Created: 'string',
	DateTime_Created: 'DateTime',
	User_Id_Modified: 'int',
	User_Name_Modified: 'string',
	DateTime_Modified: 'DateTime',
};
module.exports = {
	schemas
};
